#include "../../../Quality/root_setting.h"
#include "../../produceandcheck/file.h"
void Drawselfmatch(){
        const int ndeltaR=160;
        double deltaRbin[ndeltaR];
        for(int ibin=0;ibin<20;ibin++)
            deltaRbin[ibin]=ibin*0.01;
        for(int ibin=20;ibin<100;ibin++)
            deltaRbin[ibin]=0.2+(ibin-20)*0.05;
        for(int ibin=100;ibin<ndeltaR;ibin++)
            deltaRbin[ibin]=4.2+(ibin-100)*0.1;
	gStyle->SetOptStat(kFALSE);
	gStyle->SetOptFit(kFALSE);
	gStyle->SetErrorX(0);
	TH1D* hNmatched = (TH1D*)fMCPPbSm->Get("hNmatched");
	TH1D* hNmatched1 = (TH1D*)fMCPPbSm->Get("hNmatched1");
	TH1D* hdeltaR5 = (TH1D*)fMC5PPbSm->Get("hdeltaR");
	hdeltaR5->SetName("hdeltaR5");
	TH1D* hdeltaR = (TH1D*)fMCPPbSm->Get("hdeltaR");
	hdeltaR->SetName("hdeltaR");
	TH2F* hptdeltaptfrcmatch1 = (TH2F*)fMCPPbSm->Get("hptdeltaptfrcmatch1");
	TH2F* hptdeltaptfrcmatch20 = (TH2F*)fMCPPbSm->Get("hptdeltaptfrcmatch20");
	TH2F* hptdeltaptfrcmatch21 = (TH2F*)fMCPPbSm->Get("hptdeltaptfrcmatch21");
	TH2F* hptgenptmatch1 = (TH2F*)fMCPPbSm->Get("hptgenptmatch1");
	TH2F* hptgenptmatch20 = (TH2F*)fMCPPbSm->Get("hptgenptmatch20");
	TH2F* hptgenptmatch21 = (TH2F*)fMCPPbSm->Get("hptgenptmatch21");
	TH2F* hdeltaRdeltaptfrcmatch1 = (TH2F*)fMCPPbSm->Get("hdeltaRdeltaptfrcmatch1");
	TH2F* hdeltaRdeltaptfrcmatch20 = (TH2F*)fMCPPbSm->Get("hdeltaRdeltaptfrcmatch20");
	TH2F* hdeltaRdeltaptfrcmatch21 = (TH2F*)fMCPPbSm->Get("hdeltaRdeltaptfrcmatch21");
	TCanvas *c1 = new TCanvas("c1","c1",1200,600);
	TCanvas *c2 = new TCanvas("c2","c2",1200,600);
	TCanvas *c3 = new TCanvas("c3","c3",1200,1200);
	TCanvas *c4 = new TCanvas("c4","c4",1200,600);
	TCanvas *c5 = new TCanvas("c5","c5",1200,600);
        TH1D* hdeltaR = (TH1D*)hdeltaR->Rebin(ndeltaR-1,"hdeltaR_",deltaRbin);
        normalizeByBinWidth(hdeltaR);
        hdeltaR->Scale(0.01);
        TH1D* hdeltaR5 = (TH1D*)hdeltaR5->Rebin(ndeltaR-1,"hdeltaR5_",deltaRbin);
        normalizeByBinWidth(hdeltaR5);
        hdeltaR5->Scale(0.01);
	TLatex tl;
	tl.SetNDC();
	tl.SetTextSize(0.04);
	double ptcut=0.5;
        c1->Divide(2,1);
	c1->cd(1)->SetLogy();
	hFrame = new TH1D("hFrame","hFrame",1000,0,1000);
	hFrame->SetTitle("");
	fixedFontHist(hFrame,1.2,1.3);
	hFrame->GetXaxis()->SetTitle("matched gen");
	hFrame->GetYaxis()->SetTitle("jet cross section");
	hFrame->GetXaxis()->SetRangeUser(0,4);
	hFrame->GetYaxis()->SetRangeUser(1e-11,1);
	hFrame->DrawCopy();
	fixedFontHist(hFrame,1.2,1.4);
	hNmatched->SetMarkerSize(1.2);
	hNmatched->SetMarkerColor(2);
	hNmatched->SetMarkerStyle(20);
	hNmatched->SetMarkerColor(1);
	hNmatched1->SetMarkerSize(1.2);
	hNmatched1->SetMarkerStyle(24);
	hNmatched->Draw("Psame");
	hNmatched1->Draw("Psame");
        TLegend *tg = new TLegend(0.55,0.58,0.8,0.85);
        tg->SetBorderSize(0);
        tg->SetFillColor(0);
        tg->SetTextSize(0.03);
        tg->AddEntry(hNmatched,"|#eta_{lab}|<2","lp");
        tg->AddEntry(hNmatched1,Form("#frac{#Delta p_{T}}{p^{reco}_{T}}<%.1f |#eta_{lab}|<2",ptcut));
        tg->Draw("same");
	c1->cd(2)->SetLogy();
	hFrame1 = new TH1D("hFrame1","hFrame1",100,0,10);
	fixedFontHist(hFrame1,1.2,1.3);
	hFrame1->SetTitle("");
	hFrame1->GetXaxis()->SetTitle("#Delta R");
	hFrame1->GetYaxis()->SetTitle("jet cross section");
	hFrame1->GetXaxis()->SetRangeUser(0,5);
	hFrame1->GetYaxis()->SetRangeUser(1e-11,1);
	hFrame1->DrawCopy();
	hdeltaR->SetMarkerSize(1.1);
	hdeltaR->SetMarkerStyle(20);
	hdeltaR5->SetMarkerSize(1.1);
	hdeltaR5->SetMarkerStyle(30);
	hdeltaR5->SetMarkerColor(6);
	hdeltaR->Draw("Psame");
	hdeltaR5->Draw("Psame");
	TLegend *tg_ = new TLegend(*tg);
	tg_->SetY1(0.70);
	tg_->SetY2(0.88);
	tg_->Clear();
        tg_->AddEntry(hdeltaR,"|#eta_{lab}|<2, akPu3PF","lp");
	tg_->AddEntry(hdeltaR5,"|#eta_{lab}|<2, akPu5PF","lp");
	tg_->Draw("same");
	TLine *l = new TLine(0.3,0,0.3,1);
	l->SetLineStyle(2);
	l->Draw("same");	
/*	c2->SetRightMargin(0.12);
	hFrame2 = new TH2F("hFrame2","hFrame2",1000,0,1000,100,0.,10.);
	fixedFontHist(hFrame2,1.2,1.3);
	hFrame2->SetTitle("");
	hFrame2->GetXaxis()->SetTitle("p^{reco}_{T}");
	hFrame2->GetYaxis()->SetTitle("|p^{reco}_{T}-p^{gen}_{T}|/p^{reco}_{T}");
	hFrame2->GetXaxis()->SetRangeUser(0,1000);
	hFrame2->GetYaxis()->SetRangeUser(0,10);
	hFrame2->DrawCopy();
	tl.DrawLatex(0.4,0.4,"One jet matched case");
	hptdeltaptfrcmatch1->Draw("colz same");
        */

        c2->Divide(2,1);
	c2->cd(1)->SetLogz();
	c2->SetRightMargin(0.15);
	hFrame3 = new TH2F("hFrame3","hFrame3",1000,0,1000,100,0.,1000.);
	fixedFontHist(hFrame3,1.2,1.3);
	hFrame3->SetTitle("");
	hFrame3->GetXaxis()->SetTitle("p^{reco}_{T}");
	hFrame3->GetYaxis()->SetTitle("p^{gen}_{T}");
	hFrame3->GetXaxis()->SetRangeUser(20,400);
	hFrame3->GetYaxis()->SetRangeUser(20,400);
	hFrame3->DrawCopy();
	tl.DrawLatex(0.5,0.3,"One jet matched case");
	hptgenptmatch1->Draw("colz same");
	
        c2->cd(2)->SetLogz();
 //       c2->cd(2)->SetLogx();
 //       c2->cd(2)->SetLogy();
	c2->SetRightMargin(0.15);
	hFrame4 = new TH2F("hFrame4","hFrame4",1000,0,10.,1000,0.,10.);
	fixedFontHist(hFrame4,1.2,1.3);
	hFrame4->SetTitle("");
	hFrame4->GetXaxis()->SetTitle("#Delta R");
	hFrame4->GetYaxis()->SetTitle("|p^{reco}_{T}-p^{gen}_{T}|/p^{reco}_{T}");
	hFrame4->GetXaxis()->SetRangeUser(1e-2,0.5);
	hFrame4->GetYaxis()->SetRangeUser(1e-2,1);
	hFrame4->DrawCopy();
        hdeltaRdeltaptfrcmatch1->Draw("colz same");
	tl.DrawLatex(0.5,0.3,"One jet matched case");

        c3->Divide(2,2);
	c3->cd(1)->SetLogz();
	c3->SetRightMargin(0.15);
	fixedFontHist(hFrame3,1.5,1.7);
	hFrame3->DrawCopy();
	hptgenptmatch20->Draw("colz same");
	tl.DrawLatex(0.5,0.3,"Two jet matched, smaller #DeltaR");
	
        c3->cd(2)->SetLogz();
	c3->SetRightMargin(0.15);
	hFrame3->DrawCopy();
	hptgenptmatch21->Draw("colz same");
	tl.DrawLatex(0.5,0.3,"Two jet matched, larger #DeltaR");

	c3->cd(3)->SetLogz();
//	c3->cd(3)->SetLogx();
//	c3->cd(3)->SetLogy();
	c3->SetRightMargin(0.15);
	fixedFontHist(hFrame4,1.5,1.7);
	hFrame4->DrawCopy();
	hdeltaRdeltaptfrcmatch20->Draw("colz same");
	tl.DrawLatex(0.6,0.3,"#splitline{Two jet matched}{smaller #DeltaR}");
	
        c3->cd(4)->SetLogz();
//	c3->cd(4)->SetLogx();
//	c3->cd(4)->SetLogy();
	c3->SetRightMargin(0.15);
	hFrame4->DrawCopy();
	hdeltaRdeltaptfrcmatch21->Draw("colz same");
	tl.DrawLatex(0.6,0.3,"#splitline{Two jet matched}{larger #DeltaR}");

        c4->Divide(2,1);
        c4->cd(1);
        TProfile *ProfdRdptfrcmatch20 = (TProfile*)hdeltaRdeltaptfrcmatch20->ProfileX();
        TH1D *hdptfrcmatch20 = (TH1D*)hdeltaRdeltaptfrcmatch20->ProjectionY();
	c4->cd(1)->SetRightMargin(0.15);
	fixedFontHist(hFrame4,1.2,1.3);
	hFrame4->GetXaxis()->SetRangeUser(0,0.5);
	hFrame4->GetYaxis()->SetRangeUser(0,1.0);
	hFrame4->DrawCopy();
	ProfdRdptfrcmatch20->SetMarkerSize(1.2);
	ProfdRdptfrcmatch20->SetMarkerColor(1);
	ProfdRdptfrcmatch20->SetLineColor(1);
	ProfdRdptfrcmatch20->SetMarkerStyle(20);
	ProfdRdptfrcmatch20->Draw("Psame");
	tl.DrawLatex(0.6,0.3,"#splitline{Two jet matched}{smaller #DeltaR}");
	tl.DrawLatex(0.5,0.8,Form("removed %.2f%%",100-(double)hdptfrcmatch20->Integral(0,hdptfrcmatch20->GetXaxis()->FindBin(ptcut-1e-4))/hdptfrcmatch20->Integral()*100));
	TLine *l = new TLine(0,ptcut,0.5,ptcut);
	l->SetLineStyle(2);
	l->Draw("same");
        c4->cd(2);
        TProfile *ProfdRdptfrcmatch21 = (TProfile*)hdeltaRdeltaptfrcmatch21->ProfileX();
        TH1D *hdptfrcmatch21 = (TH1D*)hdeltaRdeltaptfrcmatch21->ProjectionY();
	c4->SetRightMargin(0.15);
	hFrame4->DrawCopy();
	ProfdRdptfrcmatch21->SetMarkerSize(1.2);
	ProfdRdptfrcmatch21->SetMarkerColor(1);
	ProfdRdptfrcmatch21->SetLineColor(1);
	ProfdRdptfrcmatch21->SetMarkerStyle(20);
	ProfdRdptfrcmatch21->Draw("Psame");
	tl.DrawLatex(0.6,0.3,"#splitline{Two jet matched}{larger #DeltaR}");
	tl.DrawLatex(0.5,0.8,Form("removed %.2f%%",100-(double)hdptfrcmatch21->Integral(0,hdptfrcmatch21->GetXaxis()->FindBin(ptcut-1e-4))/hdptfrcmatch21->Integral()*100));
	l->Draw("same");


        c5->Divide(2,1);
        c5->cd(1)->SetLogy();
        TH1D *hdptfrcmatch1 = (TH1D*)hdeltaRdeltaptfrcmatch1->ProjectionY();
	fixedFontHist(hFrame1,1.2,1.3);
	hFrame1->GetXaxis()->SetRangeUser(0,2);
	hFrame1->GetYaxis()->SetRangeUser(1e-9,1e-1);
	hFrame1->GetXaxis()->SetTitle("|p^{reco}_{T}-p^{gen}_{T}|/p^{reco}_{T}");
	hFrame1->DrawCopy();
	hdptfrcmatch1->SetMarkerSize(1.2);
	hdptfrcmatch1->SetMarkerStyle(20);
	hdptfrcmatch1->SetMarkerColor(1);
	hdptfrcmatch1->SetLineColor(1);
	hdptfrcmatch1->Draw("Psame");
	tl.DrawLatex(0.5,0.8,Form("removed %.2f%%",100-(double)hdptfrcmatch1->Integral(0,hdptfrcmatch1->GetXaxis()->FindBin(ptcut-1e-4))/hdptfrcmatch1->Integral()*100));
	tl.DrawLatex(0.6,0.3,"One jet matched");
	TLine *l = new TLine(ptcut,0,ptcut,1e-1);
	l->SetLineStyle(2);
	l->Draw("same");
        c5->cd(2);
	c5->cd(2)->SetLeftMargin(0.1);
        TProfile *ProfdRdptfrcmatch1 = (TProfile*)hdeltaRdeltaptfrcmatch1->ProfileX();
	hFrame4->GetXaxis()->SetRangeUser(0,0.35);
	hFrame4->GetYaxis()->SetRangeUser(0,0.8);
	hFrame4->GetXaxis()->SetTitle("#Delta R");
	hFrame4->DrawCopy();
	ProfdRdptfrcmatch1->SetMarkerSize(1.2);
	ProfdRdptfrcmatch1->SetMarkerStyle(20);
	ProfdRdptfrcmatch1->SetMarkerColor(1);
	ProfdRdptfrcmatch1->SetLineColor(1);
	ProfdRdptfrcmatch1->Draw("Psame");
	tl.DrawLatex(0.6,0.6,"One jet matched");
	TLine *l = new TLine(0,ptcut,0.35,ptcut);
	l->SetLineStyle(2);
	l->Draw("same");

	c1->Print("MatchQuality.png");
        c2->Print("match1.png");
	c3->Print("match2.png");
        c4->Print("match2Prof.png");
        c5->Print("match1Proj.png");
}

