#include <iomanip>
#include "../../../jetRpA/RpA/Quality/root_setting.h"

void plotqdisallbins(){
    int marker[] = {20,34,33,24,27,28,24,21,33};
    int color[] = {1,2,2,9,6,4,8,1,2};
    int xtheta=0;
    gStyle->SetOptStat(0);
    gStyle->SetOptFit(1111);
    const int ntotbins = 5;
    const int nnonf = 2;
    int xbin=0;
    TString dir[ntotbins]={"M150120","M185150","M220185","M260220","M300260"};
    TLatex *t= new TLatex();
    t->SetNDC();
    t->SetTextSize(0.04);
    t->SetTextFont(42);
    TCanvas *c4 = new TCanvas("c4","c4",1000,500);
    c4->Divide(2,1);
    TLegend *tl = new TLegend(0.60,0.65,0.80,0.85);
    tl->SetTextSize(0.035);
    tl->SetBorderSize(0);
    tl->SetFillColor(0);
    TH1D* hFrame = new TH1D("","",1000,0,10);

    for(int ibin=0;ibin<ntotbins;ibin++){
        TFile *f = TFile::Open(Form("%s/mergedV_Sum.root",dir[ibin].Data()));
        TVectorD *vecDavgmult = (TVectorD*)f->Get(Form("avgmultall"));
        TVectorD *vecDavgtrk = (TVectorD*)f->Get(Form("avgtrk"));
        double *avgmult = vecDavgmult->GetMatrixArray();
        double *avgtrk = vecDavgtrk->GetMatrixArray();
//        for(int ibin=0;ibin<nbin;ibin++){	//ibin<1
            TH1D* hq = (TH1D*)f->Get(Form("D_%d/D_%d/hq",xbin,xtheta));
            TH1D* hqx = (TH1D*)f->Get(Form("D_%d/hqx",xbin));
            TH1D* hqy = (TH1D*)f->Get(Form("D_%d/hqy",xbin));
            TH1D* hq2 = (TH1D*)f->Get(Form("D_%d/hq2",xbin));
            hq2->Rebin(10);
            TH1D* hq2nonf = (TH1D*)f->Get(Form("D_%d/hq2nonf",xbin));
            hq2nonf->Rebin(10);
        //multiplyByBinCenter(hq);
        hq->Scale(1./hq->Integral(0,-1,"width"));
        //normalizeByBinWidth(hq);
        //multiplyByBinCenter(hqx);
        hqx->Scale(1./hqx->Integral(0,-1,"width"));
        //normalizeByBinWidth(hqx);
        //multiplyByBinCenter(hqy);
        hqy->Scale(1./hqy->Integral(0,-1,"width"));
        //normalizeByBinWidth(hqy);
        hq2->Scale(1./hq2->Integral(0,-1,"width"));
        hq2nonf->Scale(1./hq2nonf->Integral(0,-1,"width"));
/*ffit = new TF1(Form("ffit"),"1./(0.5*(1+[0]))*TMath::Exp(-([1]*[1]*[2]+x*x)/(1+[0]))*TMath::BesselI0(x*[1]*TMath::Sqrt([2])/(0.5*(1+[0])))",0,10);
f1fit = new TF1(Form("f1fit"),"x/(0.5*(1+[0]))*TMath::Exp(-([1]*[1]*[2]+x*x)/(1+[0]))*TMath::BesselI0(x*[1]*TMath::Sqrt([2])/(0.5*(1+[0])))",0,10);
//ffit = new TF1(Form("ffit"),"1./([0])*TMath::Exp(-([1]*[1]*[2]+x*x)/(2*[0]))*TMath::BesselI0(x*[1]*TMath::Sqrt([2])/([0]))",0,10);
//f1fit = new TF1(Form("f1fit"),"x/([0])*TMath::Exp(-([1]*[1]*[2]+x*x)/(2*[0]))*TMath::BesselI0(x*[1]*TMath::Sqrt([2])/([0]))",0,10);
ffit->SetParNames("g2","v2","M");
f1fit->SetParNames("g2","v2","M");
//ffit->SetParNames("#sigma2","v2","M");
//f1fit->SetParNames("sigma2","v2","M");
ffit->SetParameters(0.1,0.05,avgmult[ibin]);
f1fit->SetParameters(0.1,0.05,avgmult[ibin]);
//ffit->FixParameter(1,0);
//f1fit->FixParameter(1,0);
//f1fit->FixParameter(0,0);
ffit->FixParameter(2,avgmult[ibin]);
f1fit->FixParameter(2,avgmult[ibin]);
hq->Fit(Form("f1fit"),"R","P",0,10);
TCanvas *c1 = new TCanvas("c1","c1",500,1000);
c1->Divide(1,2);
c1->cd(1)->SetLogy();
fixedFontHist(hqx,1.6,2.0);
hqx->SetTitle("");
hqx->GetXaxis()->SetTitle("q_{x}");
hqx->GetYaxis()->SetTitle("#frac{dN}{dq_{x}}");
hqx->GetYaxis()->SetRangeUser(1e-10,1);
hqx->Fit(Form("f1fit"),"R","",0,10);
c1->cd(2)->SetLogy();
TH1D* hqx_cp = (TH1D*)hqx->Clone("hqx_cp");
fixedFontHist(hqx_cp,1.6,2.0);
divideByBinCenter(hqx_cp);
hqx_cp->GetYaxis()->SetTitle("#frac{dN}{q_{x}dq_{x}}");
hqx_cp->GetYaxis()->SetRangeUser(1e-10,10);
hqx_cp->Fit(Form("ffit"),"R","",0,10);
t->DrawLatex(0.5,0.2,Form("N_{trk}^{offline} = %.2f", avgtrk[ibin]));

TCanvas *c3 = new TCanvas("c3","c3",500,1000);
c3->Divide(1,2);
c3->cd(1);
fixedFontHist(hqy,1.6,2.0);
hqy->SetTitle("");
hqy->GetXaxis()->SetTitle("q_{y}");
hqy->GetYaxis()->SetTitle("#frac{dN}{dq_{y}}");
hqy->GetYaxis()->SetRangeUser(0,1);
hqy->SetMarkerStyle(24);
hqy->SetMarkerSize(0.5);
hqy->Fit(Form("f1fit"),"R","",0,10);
hqy->Draw("Psame");
c3->cd(2)->SetLogy();
TH1D* hqy_cp = (TH1D*)hqy->Clone("hqy_cp");
fixedFontHist(hqy_cp,1.6,2.0);
divideByBinCenter(hqy_cp);
hqy_cp->GetYaxis()->SetTitle("#frac{dN}{q_{y}dq_{y}}");
hqy_cp->GetYaxis()->SetRangeUser(1e-10,10);
hqy_cp->SetMarkerStyle(24);
hqy_cp->SetMarkerSize(0.5);
hqy_cp->Fit(Form("ffit"),"R","",0,10);
hqy_cp->Draw("Psame");
t->DrawLatex(0.5,0.2,Form("N_{trk}^{offline} = %.2f",avgtrk[ibin]));
*/
c4->cd(1)->SetLeftMargin(0.18);
fixedFontHist(hFrame,1.0,2.0);
hFrame->GetXaxis()->SetTitle("q2");
hFrame->GetYaxis()->SetTitle("#frac{dN}{dq_{2}}");
hFrame->GetYaxis()->SetRangeUser(0,1);
if(ibin==0)
hFrame->DrawCopy();
hq2->SetMarkerStyle(marker[ibin]);
hq2->SetMarkerColor(color[ibin]);
hq2->SetLineColor(color[ibin]);
hq2->SetMarkerSize(0.5);
hq2->Draw("Psame");
c4->cd(2)->SetLogy();
c4->cd(2)->SetLeftMargin(0.2);
TH1D* hq2_cp = (TH1D*)hq2->Clone("hq2_cp");
fixedFontHist(hFrame,1.0,2.0);
divideByBinCenter(hq2_cp);
hFrame->GetYaxis()->SetTitle("#frac{dN}{q_{2}dq_{2}}");
hFrame->GetYaxis()->SetRangeUser(1e-10,10);
if(ibin==0)
hFrame->DrawCopy();
hq2_cp->SetMarkerStyle(marker[ibin]);
hq2_cp->SetMarkerColor(color[ibin]);
hq2_cp->SetLineColor(color[ibin]);
hq2_cp->SetMarkerSize(0.5);
hq2_cp->Draw("Psame");
tl->AddEntry(hq2,Form("N_{trk}^{offline} = %.2f", avgtrk[xbin]));
/*
TCanvas *c5 = new TCanvas("c5","c5",500,1000);
c5->Divide(1,2);
c5->cd(1);
fixedFontHist(hq2nonf,1.6,2.0);
hq2nonf->SetTitle("");
hq2nonf->GetXaxis()->SetTitle("q_{2}");
hq2nonf->GetYaxis()->SetTitle("#frac{dN}{dq_{2}}");
hq2nonf->GetYaxis()->SetRangeUser(0,1);
hq2nonf->SetMarkerStyle(24);
hq2nonf->SetMarkerColor(4);
hq2nonf->SetLineColor(4);
hq2nonf->SetMarkerSize(0.5);
ffit->SetParameters(1.5,0.05,avgmult[ibin]*2);
f1fit->SetParameters(1.5,0.05,avgmult[ibin]*2);
ffit->FixParameter(2,avgmult[ibin]*2);
f1fit->FixParameter(2,avgmult[ibin]*2);
//ffit->FixParameter(1,0);
//f1fit->FixParameter(1,0);
//ffit->FixParameter(0,1);
//f1fit->FixParameter(0,1);
hq2nonf->Fit(Form("f1fit"),"R","",0,10);
TVectorD vecrnonf;
vecrnonf.ResizeTo(6);
vecrnonf[0]=f1fit->GetParameter(0);
vecrnonf[1]=f1fit->GetParError(0);
vecrnonf[2]=f1fit->GetParameter(1);
vecrnonf[3]=f1fit->GetParError(1);
vecrnonf[4]=avgmult[ibin];
vecrnonf[5]=avgtrk[ibin];
hq2nonf->Draw("Psame");
c5->cd(2)->SetLogy();
TH1D* hq2nonf_cp = (TH1D*)hq2nonf->Clone("hq2nonf_cp");
fixedFontHist(hq2nonf_cp,1.6,2.0);
divideByBinCenter(hq2nonf_cp);
hq2nonf_cp->GetYaxis()->SetTitle("#frac{dN}{q_{2}dq_{2}}");
hq2nonf_cp->GetYaxis()->SetRangeUser(1e-10,10);
hq2nonf_cp->SetMarkerStyle(24);
hq2nonf_cp->SetMarkerColor(4);
hq2nonf_cp->SetLineColor(4);
hq2nonf_cp->SetMarkerSize(0.5);
hq2nonf_cp->Fit(Form("ffit"),"R","",0,10);
hq2nonf_cp->Draw("Psame");
t->DrawLatex(0.5,0.2,Form("N_{trk}^{offline} = %.2f", avgtrk[ibin]*2));
*/
}
c4->cd(1);
tl->Draw("same");
/*
c1->Print("hqx_fit.png");
c3->Print("hqy_fit.png");
c4->Print("hq2_fit.png");
c5->Print("hq2nonf_fit.png");
*/
c4->Print("hq2_fit.png");
}

