/********************************************************************
* tmp/slc6_amd64_gcc472/src/DataFormats/HeavyIonEvent/src/DataFormatsHeavyIonEvent/DataFormatsHeavyIonEvent_LinkDef.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/slc6_amd64_gcc472/src/DataFormats/HeavyIonEvent/src/DataFormatsHeavyIonEvent/DataFormatsHeavyIonEvent_LinkDef.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDataFormatsHeavyIonEvent_LinkDef();
extern void G__cpp_setup_inheritanceDataFormatsHeavyIonEvent_LinkDef();
extern void G__cpp_setup_typetableDataFormatsHeavyIonEvent_LinkDef();
extern void G__cpp_setup_memvarDataFormatsHeavyIonEvent_LinkDef();
extern void G__cpp_setup_globalDataFormatsHeavyIonEvent_LinkDef();
extern void G__cpp_setup_memfuncDataFormatsHeavyIonEvent_LinkDef();
extern void G__cpp_setup_funcDataFormatsHeavyIonEvent_LinkDef();
extern void G__set_cpp_environmentDataFormatsHeavyIonEvent_LinkDef();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_TClass;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_TBuffer;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_TMemberInspector;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_TObject;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_TNamed;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_CBin;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_maplEintcOconstsPCentralityBinsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPCentralityBinsmUgRsPgRsPgR;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlECBincOallocatorlECBingRsPgR;
extern G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlECBincOallocatorlECBingRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
