#ifndef __Cent_Bin_h__
#include "DataFormats/HeavyIonEvent/interface/CentralityBins.h"
#define __Cent_Bin_h__
#endif

#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ nestedclass;
#pragma link C++ nestedtypedef;
#pragma link C++ class CentralityBins+;
#pragma link C++ class CBin+;

#endif
//
// File generated by /cvmfs/cms.cern.ch/slc6_amd64_gcc472/lcg/root/5.32.00-cms/bin/rootcint at Tue Apr 14 11:28:01 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME tmpdIslc6_amd64_gcc472dIsrcdIDataFormatsdIHeavyIonEventdIsrcdIDataFormatsHeavyIonEventdIDataFormatsHeavyIonEvent_LinkDef
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DataFormatsHeavyIonEvent_LinkDef.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void CBin_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_CBin(void *p = 0);
   static void *newArray_CBin(Long_t size, void *p);
   static void delete_CBin(void *p);
   static void deleteArray_CBin(void *p);
   static void destruct_CBin(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CBin*)
   {
      ::CBin *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CBin >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CBin", ::CBin::Class_Version(), "/gpfs22/home/xuq7/HI/CMSSW_5_3_20/src/DataFormats/HeavyIonEvent/interface/CentralityBins.h", 9,
                  typeid(::CBin), DefineBehavior(ptr, ptr),
                  &::CBin::Dictionary, isa_proxy, 4,
                  sizeof(::CBin) );
      instance.SetNew(&new_CBin);
      instance.SetNewArray(&newArray_CBin);
      instance.SetDelete(&delete_CBin);
      instance.SetDeleteArray(&deleteArray_CBin);
      instance.SetDestructor(&destruct_CBin);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CBin*)
   {
      return GenerateInitInstanceLocal((::CBin*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CBin*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void CentralityBins_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_CentralityBins(void *p = 0);
   static void *newArray_CentralityBins(Long_t size, void *p);
   static void delete_CentralityBins(void *p);
   static void deleteArray_CentralityBins(void *p);
   static void destruct_CentralityBins(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CentralityBins*)
   {
      ::CentralityBins *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CentralityBins >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CentralityBins", ::CentralityBins::Class_Version(), "/gpfs22/home/xuq7/HI/CMSSW_5_3_20/src/DataFormats/HeavyIonEvent/interface/CentralityBins.h", 37,
                  typeid(::CentralityBins), DefineBehavior(ptr, ptr),
                  &::CentralityBins::Dictionary, isa_proxy, 4,
                  sizeof(::CentralityBins) );
      instance.SetNew(&new_CentralityBins);
      instance.SetNewArray(&newArray_CentralityBins);
      instance.SetDelete(&delete_CentralityBins);
      instance.SetDeleteArray(&deleteArray_CentralityBins);
      instance.SetDestructor(&destruct_CentralityBins);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CentralityBins*)
   {
      return GenerateInitInstanceLocal((::CentralityBins*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CentralityBins*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *CBin::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CBin::Class_Name()
{
   return "CBin";
}

//______________________________________________________________________________
const char *CBin::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CBin*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CBin::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CBin*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CBin::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CBin*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CBin::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CBin*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *CentralityBins::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CentralityBins::Class_Name()
{
   return "CentralityBins";
}

//______________________________________________________________________________
const char *CentralityBins::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CentralityBins*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CentralityBins::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CentralityBins*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CentralityBins::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CentralityBins*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CentralityBins::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CentralityBins*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void CentralityBins::Streamer(TBuffer &R__b)
{
   // Stream an object of class CentralityBins.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(CentralityBins::Class(),this);
   } else {
      R__b.WriteClassBuffer(CentralityBins::Class(),this);
   }
}

//______________________________________________________________________________
void CentralityBins::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class CentralityBins.
      TClass *R__cl = ::CentralityBins::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "table_", (void*)&table_);
      R__insp.InspectMember("vector<CBin>", (void*)&table_, "table_.", false);
      TNamed::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_CentralityBins(void *p) {
      return  p ? new(p) ::CentralityBins : new ::CentralityBins;
   }
   static void *newArray_CentralityBins(Long_t nElements, void *p) {
      return p ? new(p) ::CentralityBins[nElements] : new ::CentralityBins[nElements];
   }
   // Wrapper around operator delete
   static void delete_CentralityBins(void *p) {
      delete ((::CentralityBins*)p);
   }
   static void deleteArray_CentralityBins(void *p) {
      delete [] ((::CentralityBins*)p);
   }
   static void destruct_CentralityBins(void *p) {
      typedef ::CentralityBins current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::CentralityBins

//______________________________________________________________________________
void CBin::Streamer(TBuffer &R__b)
{
   // Stream an object of class CBin.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(CBin::Class(),this);
   } else {
      R__b.WriteClassBuffer(CBin::Class(),this);
   }
}

//______________________________________________________________________________
void CBin::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class CBin.
      TClass *R__cl = ::CBin::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bin_edge", &bin_edge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "n_part_mean", &n_part_mean);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "n_part_var", &n_part_var);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "n_coll_mean", &n_coll_mean);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "n_coll_var", &n_coll_var);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "n_hard_mean", &n_hard_mean);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "n_hard_var", &n_hard_var);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "b_mean", &b_mean);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "b_var", &b_var);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "eccRP_mean", &eccRP_mean);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "eccRP_var", &eccRP_var);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ecc2_mean", &ecc2_mean);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ecc2_var", &ecc2_var);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ecc3_mean", &ecc3_mean);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ecc3_var", &ecc3_var);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "s_mean", &s_mean);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "s_var", &s_var);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_CBin(void *p) {
      return  p ? new(p) ::CBin : new ::CBin;
   }
   static void *newArray_CBin(Long_t nElements, void *p) {
      return p ? new(p) ::CBin[nElements] : new ::CBin[nElements];
   }
   // Wrapper around operator delete
   static void delete_CBin(void *p) {
      delete ((::CBin*)p);
   }
   static void deleteArray_CBin(void *p) {
      delete [] ((::CBin*)p);
   }
   static void destruct_CBin(void *p) {
      typedef ::CBin current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::CBin

namespace ROOT {
   void vectorlECBingR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlECBingR_Dictionary();
   static void *new_vectorlECBingR(void *p = 0);
   static void *newArray_vectorlECBingR(Long_t size, void *p);
   static void delete_vectorlECBingR(void *p);
   static void deleteArray_vectorlECBingR(void *p);
   static void destruct_vectorlECBingR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<CBin>*)
   {
      vector<CBin> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<CBin>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<CBin>", -2, "/cvmfs/cms.cern.ch/slc6_amd64_gcc472/lcg/root/5.32.00-cms/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<CBin>), DefineBehavior(ptr, ptr),
                  0, &vectorlECBingR_Dictionary, isa_proxy, 0,
                  sizeof(vector<CBin>) );
      instance.SetNew(&new_vectorlECBingR);
      instance.SetNewArray(&newArray_vectorlECBingR);
      instance.SetDelete(&delete_vectorlECBingR);
      instance.SetDeleteArray(&deleteArray_vectorlECBingR);
      instance.SetDestructor(&destruct_vectorlECBingR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<CBin> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<CBin>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlECBingR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<CBin>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlECBingR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<CBin> : new vector<CBin>;
   }
   static void *newArray_vectorlECBingR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<CBin>[nElements] : new vector<CBin>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlECBingR(void *p) {
      delete ((vector<CBin>*)p);
   }
   static void deleteArray_vectorlECBingR(void *p) {
      delete [] ((vector<CBin>*)p);
   }
   static void destruct_vectorlECBingR(void *p) {
      typedef vector<CBin> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<CBin>

/********************************************************
* tmp/slc6_amd64_gcc472/src/DataFormats/HeavyIonEvent/src/DataFormatsHeavyIonEvent/DataFormatsHeavyIonEvent_LinkDef.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDataFormatsHeavyIonEvent_LinkDef();

extern "C" void G__set_cpp_environmentDataFormatsHeavyIonEvent_LinkDef() {
  G__cpp_reset_tagtableDataFormatsHeavyIonEvent_LinkDef();
}
#include <new>
extern "C" int G__cpp_dllrevDataFormatsHeavyIonEvent_LinkDef() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CBin */
static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CBin* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CBin[n];
     } else {
       p = new((void*) gvp) CBin[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CBin;
     } else {
       p = new((void*) gvp) CBin;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CBin));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CBin::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CBin::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CBin::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CBin::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CBin*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CBin::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CBin::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CBin::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CBin::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CBin* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CBin(*(CBin*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CBin));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CBin G__TCBin;
static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CBin*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CBin*) (soff+(sizeof(CBin)*i)))->~G__TCBin();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CBin*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CBin*) (soff))->~G__TCBin();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DataFormatsHeavyIonEvent_LinkDef_454_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CBin* dest = (CBin*) G__getstructoffset();
   *dest = *(CBin*) libp->para[0].ref;
   const CBin& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* CentralityBins */
static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CentralityBins* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CentralityBins[n];
     } else {
       p = new((void*) gvp) CentralityBins[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CentralityBins;
     } else {
       p = new((void*) gvp) CentralityBins;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CentralityBins* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new CentralityBins(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) CentralityBins(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const CentralityBins*) G__getstructoffset())->getBin((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const CentralityBins*) G__getstructoffset())->getNbins());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->lowEdge((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->lowEdgeOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NpartMean((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NpartMeanOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NpartSigma((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NpartSigmaOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NcollMean((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NcollMeanOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NcollSigma((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NcollSigmaOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NhardMean((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NhardMeanOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NhardSigma((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->NhardSigmaOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->bMean((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->bMeanOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->bSigma((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->bSigmaOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->eccentricityRPMean((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->eccentricityRPMeanOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->eccentricityRPSigma((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->eccentricityRPSigmaOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->eccentricityMean((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->eccentricityMeanOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->eccentricitySigma((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->eccentricitySigmaOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->triangularityMean((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->triangularityMeanOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->triangularitySigma((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->triangularitySigmaOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->areaMean((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->areaMeanOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->areaSigma((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const CentralityBins*) G__getstructoffset())->areaSigmaOfBin((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CentralityBins::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CentralityBins::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CentralityBins::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CentralityBins::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CentralityBins*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CentralityBins::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CentralityBins::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CentralityBins::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CentralityBins::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CentralityBins* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CentralityBins(*(CentralityBins*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CentralityBins G__TCentralityBins;
static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CentralityBins*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CentralityBins*) (soff+(sizeof(CentralityBins)*i)))->~G__TCentralityBins();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CentralityBins*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CentralityBins*) (soff))->~G__TCentralityBins();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DataFormatsHeavyIonEvent_LinkDef_455_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CentralityBins* dest = (CentralityBins*) G__getstructoffset();
   *dest = *(CentralityBins*) libp->para[0].ref;
   const CentralityBins& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CBin */

/* CentralityBins */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDataFormatsHeavyIonEvent_LinkDef {
 public:
  G__Sizep2memfuncDataFormatsHeavyIonEvent_LinkDef(): p(&G__Sizep2memfuncDataFormatsHeavyIonEvent_LinkDef::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDataFormatsHeavyIonEvent_LinkDef::*p)();
};

size_t G__get_sizep2memfuncDataFormatsHeavyIonEvent_LinkDef()
{
  G__Sizep2memfuncDataFormatsHeavyIonEvent_LinkDef a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDataFormatsHeavyIonEvent_LinkDef() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CBin))) {
     CBin *G__Lderived;
     G__Lderived=(CBin*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CBin),G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins))) {
     CentralityBins *G__Lderived;
     G__Lderived=(CentralityBins*)0x1000;
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins),G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins),G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDataFormatsHeavyIonEvent_LinkDef() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,const CentralityBins*>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_maplEintcOconstsPCentralityBinsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPCentralityBinsmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,const CentralityBins*,less<int> >",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_maplEintcOconstsPCentralityBinsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPCentralityBinsmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("RunMap",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_maplEintcOconstsPCentralityBinsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPCentralityBinsmUgRsPgRsPgR),0,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<CBin>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlECBincOallocatorlECBingRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlECBincOallocatorlECBingRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlECBincOallocatorlECBingRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlECBincOallocatorlECBingRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlECBincOallocatorlECBingRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CBin */
static void G__setup_memvarCBin(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CBin));
   { CBin *p; p=(CBin*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->bin_edge)-(long)(p)),102,0,0,-1,-1,-1,1,"bin_edge=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->n_part_mean)-(long)(p)),102,0,0,-1,-1,-1,1,"n_part_mean=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->n_part_var)-(long)(p)),102,0,0,-1,-1,-1,1,"n_part_var=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->n_coll_mean)-(long)(p)),102,0,0,-1,-1,-1,1,"n_coll_mean=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->n_coll_var)-(long)(p)),102,0,0,-1,-1,-1,1,"n_coll_var=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->n_hard_mean)-(long)(p)),102,0,0,-1,-1,-1,1,"n_hard_mean=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->n_hard_var)-(long)(p)),102,0,0,-1,-1,-1,1,"n_hard_var=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_mean)-(long)(p)),102,0,0,-1,-1,-1,1,"b_mean=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_var)-(long)(p)),102,0,0,-1,-1,-1,1,"b_var=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->eccRP_mean)-(long)(p)),102,0,0,-1,-1,-1,1,"eccRP_mean=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->eccRP_var)-(long)(p)),102,0,0,-1,-1,-1,1,"eccRP_var=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ecc2_mean)-(long)(p)),102,0,0,-1,-1,-1,1,"ecc2_mean=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ecc2_var)-(long)(p)),102,0,0,-1,-1,-1,1,"ecc2_var=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ecc3_mean)-(long)(p)),102,0,0,-1,-1,-1,1,"ecc3_mean=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ecc3_var)-(long)(p)),102,0,0,-1,-1,-1,1,"ecc3_var=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->s_mean)-(long)(p)),102,0,0,-1,-1,-1,1,"s_mean=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->s_var)-(long)(p)),102,0,0,-1,-1,-1,1,"s_var=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* CentralityBins */
static void G__setup_memvarCentralityBins(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins));
   { CentralityBins *p; p=(CentralityBins*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->table_)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlECBincOallocatorlECBingRsPgR),G__defined_typename("vector<CBin>"),-1,1,"table_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDataFormatsHeavyIonEvent_LinkDef() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCBin(void) {
   /* CBin */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CBin));
   G__memfunc_setup("CBin",348,G__DataFormatsHeavyIonEvent_LinkDef_454_0_1, 105, G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CBin), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DataFormatsHeavyIonEvent_LinkDef_454_0_2, 85, G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&CBin::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DataFormatsHeavyIonEvent_LinkDef_454_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CBin::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DataFormatsHeavyIonEvent_LinkDef_454_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&CBin::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DataFormatsHeavyIonEvent_LinkDef_454_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&CBin::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DataFormatsHeavyIonEvent_LinkDef_454_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DataFormatsHeavyIonEvent_LinkDef_454_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CBin::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DataFormatsHeavyIonEvent_LinkDef_454_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CBin::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DataFormatsHeavyIonEvent_LinkDef_454_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CBin::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DataFormatsHeavyIonEvent_LinkDef_454_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CBin::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("CBin", 348, G__DataFormatsHeavyIonEvent_LinkDef_454_0_14, (int) ('i'), G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CBin), -1, 0, 1, 1, 1, 0, "u 'CBin' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CBin", 474, G__DataFormatsHeavyIonEvent_LinkDef_454_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DataFormatsHeavyIonEvent_LinkDef_454_0_16, (int) ('u'), G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CBin), -1, 1, 1, 1, 1, 0, "u 'CBin' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncCentralityBins(void) {
   /* CentralityBins */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins));
   G__memfunc_setup("CentralityBins",1451,G__DataFormatsHeavyIonEvent_LinkDef_455_0_1, 105, G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CentralityBins",1451,G__DataFormatsHeavyIonEvent_LinkDef_455_0_2, 105, G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins), -1, 0, 3, 1, 1, 0, 
"C - - 10 - name C - - 10 - title "
"i - - 0 - nbins", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBin",601,G__DataFormatsHeavyIonEvent_LinkDef_455_0_3, 105, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getNbins",826,G__DataFormatsHeavyIonEvent_LinkDef_455_0_4, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("lowEdge",711,G__DataFormatsHeavyIonEvent_LinkDef_455_0_5, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("lowEdgeOfBin",1173,G__DataFormatsHeavyIonEvent_LinkDef_455_0_6, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NpartMean",902,G__DataFormatsHeavyIonEvent_LinkDef_455_0_7, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NpartMeanOfBin",1364,G__DataFormatsHeavyIonEvent_LinkDef_455_0_8, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NpartSigma",1014,G__DataFormatsHeavyIonEvent_LinkDef_455_0_9, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NpartSigmaOfBin",1476,G__DataFormatsHeavyIonEvent_LinkDef_455_0_10, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NcollMean",889,G__DataFormatsHeavyIonEvent_LinkDef_455_0_11, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NcollMeanOfBin",1351,G__DataFormatsHeavyIonEvent_LinkDef_455_0_12, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NcollSigma",1001,G__DataFormatsHeavyIonEvent_LinkDef_455_0_13, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NcollSigmaOfBin",1463,G__DataFormatsHeavyIonEvent_LinkDef_455_0_14, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NhardMean",878,G__DataFormatsHeavyIonEvent_LinkDef_455_0_15, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NhardMeanOfBin",1340,G__DataFormatsHeavyIonEvent_LinkDef_455_0_16, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NhardSigma",990,G__DataFormatsHeavyIonEvent_LinkDef_455_0_17, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NhardSigmaOfBin",1452,G__DataFormatsHeavyIonEvent_LinkDef_455_0_18, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("bMean",483,G__DataFormatsHeavyIonEvent_LinkDef_455_0_19, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("bMeanOfBin",945,G__DataFormatsHeavyIonEvent_LinkDef_455_0_20, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("bSigma",595,G__DataFormatsHeavyIonEvent_LinkDef_455_0_21, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("bSigmaOfBin",1057,G__DataFormatsHeavyIonEvent_LinkDef_455_0_22, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("eccentricityRPMean",1833,G__DataFormatsHeavyIonEvent_LinkDef_455_0_23, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("eccentricityRPMeanOfBin",2295,G__DataFormatsHeavyIonEvent_LinkDef_455_0_24, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("eccentricityRPSigma",1945,G__DataFormatsHeavyIonEvent_LinkDef_455_0_25, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("eccentricityRPSigmaOfBin",2407,G__DataFormatsHeavyIonEvent_LinkDef_455_0_26, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("eccentricityMean",1671,G__DataFormatsHeavyIonEvent_LinkDef_455_0_27, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("eccentricityMeanOfBin",2133,G__DataFormatsHeavyIonEvent_LinkDef_455_0_28, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("eccentricitySigma",1783,G__DataFormatsHeavyIonEvent_LinkDef_455_0_29, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("eccentricitySigmaOfBin",2245,G__DataFormatsHeavyIonEvent_LinkDef_455_0_30, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("triangularityMean",1808,G__DataFormatsHeavyIonEvent_LinkDef_455_0_31, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("triangularityMeanOfBin",2270,G__DataFormatsHeavyIonEvent_LinkDef_455_0_32, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("triangularitySigma",1920,G__DataFormatsHeavyIonEvent_LinkDef_455_0_33, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("triangularitySigmaOfBin",2382,G__DataFormatsHeavyIonEvent_LinkDef_455_0_34, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("areaMean",794,G__DataFormatsHeavyIonEvent_LinkDef_455_0_35, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("areaMeanOfBin",1256,G__DataFormatsHeavyIonEvent_LinkDef_455_0_36, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("areaSigma",906,G__DataFormatsHeavyIonEvent_LinkDef_455_0_37, 102, -1, -1, 0, 1, 1, 1, 8, "d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("areaSigmaOfBin",1368,G__DataFormatsHeavyIonEvent_LinkDef_455_0_38, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - bin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DataFormatsHeavyIonEvent_LinkDef_455_0_39, 85, G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&CentralityBins::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DataFormatsHeavyIonEvent_LinkDef_455_0_40, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CentralityBins::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DataFormatsHeavyIonEvent_LinkDef_455_0_41, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&CentralityBins::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DataFormatsHeavyIonEvent_LinkDef_455_0_42, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&CentralityBins::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DataFormatsHeavyIonEvent_LinkDef_455_0_46, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DataFormatsHeavyIonEvent_LinkDef_455_0_47, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CentralityBins::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DataFormatsHeavyIonEvent_LinkDef_455_0_48, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CentralityBins::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DataFormatsHeavyIonEvent_LinkDef_455_0_49, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CentralityBins::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DataFormatsHeavyIonEvent_LinkDef_455_0_50, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CentralityBins::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("CentralityBins", 1451, G__DataFormatsHeavyIonEvent_LinkDef_455_0_51, (int) ('i'), G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins), -1, 0, 1, 1, 1, 0, "u 'CentralityBins' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CentralityBins", 1577, G__DataFormatsHeavyIonEvent_LinkDef_455_0_52, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DataFormatsHeavyIonEvent_LinkDef_455_0_53, (int) ('u'), G__get_linked_tagnum(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins), -1, 1, 1, 1, 1, 0, "u 'CentralityBins' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDataFormatsHeavyIonEvent_LinkDef() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDataFormatsHeavyIonEvent_LinkDef() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDataFormatsHeavyIonEvent_LinkDef() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_CBin = { "CBin" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins = { "CentralityBins" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_maplEintcOconstsPCentralityBinsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPCentralityBinsmUgRsPgRsPgR = { "map<int,const CentralityBins*,less<int>,allocator<pair<const int,const CentralityBins*> > >" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlECBincOallocatorlECBingRsPgR = { "vector<CBin,allocator<CBin> >" , 99 , -1 };
G__linked_taginfo G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlECBincOallocatorlECBingRsPgRcLcLiteratorgR = { "reverse_iterator<vector<CBin,allocator<CBin> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDataFormatsHeavyIonEvent_LinkDef() {
  G__DataFormatsHeavyIonEvent_LinkDefLN_TClass.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_TBuffer.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_TMemberInspector.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_TObject.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_TNamed.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_CBin.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_maplEintcOconstsPCentralityBinsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPCentralityBinsmUgRsPgRsPgR.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlECBincOallocatorlECBingRsPgR.tagnum = -1 ;
  G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlECBincOallocatorlECBingRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDataFormatsHeavyIonEvent_LinkDef() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_TClass);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_TObject);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_TNamed);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_CBin),sizeof(CBin),-1,292096,(char*)NULL,G__setup_memvarCBin,G__setup_memfuncCBin);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_CentralityBins),sizeof(CentralityBins),-1,324864,(char*)NULL,G__setup_memvarCentralityBins,G__setup_memfuncCentralityBins);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_maplEintcOconstsPCentralityBinsmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOconstsPCentralityBinsmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_vectorlECBincOallocatorlECBingRsPgR);
   G__get_linked_tagnum_fwd(&G__DataFormatsHeavyIonEvent_LinkDefLN_reverse_iteratorlEvectorlECBincOallocatorlECBingRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupDataFormatsHeavyIonEvent_LinkDef(void) {
  G__check_setup_version(30051515,"G__cpp_setupDataFormatsHeavyIonEvent_LinkDef()");
  G__set_cpp_environmentDataFormatsHeavyIonEvent_LinkDef();
  G__cpp_setup_tagtableDataFormatsHeavyIonEvent_LinkDef();

  G__cpp_setup_inheritanceDataFormatsHeavyIonEvent_LinkDef();

  G__cpp_setup_typetableDataFormatsHeavyIonEvent_LinkDef();

  G__cpp_setup_memvarDataFormatsHeavyIonEvent_LinkDef();

  G__cpp_setup_memfuncDataFormatsHeavyIonEvent_LinkDef();
  G__cpp_setup_globalDataFormatsHeavyIonEvent_LinkDef();
  G__cpp_setup_funcDataFormatsHeavyIonEvent_LinkDef();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDataFormatsHeavyIonEvent_LinkDef();
  return;
}
class G__cpp_setup_initDataFormatsHeavyIonEvent_LinkDef {
  public:
    G__cpp_setup_initDataFormatsHeavyIonEvent_LinkDef() { G__add_setup_func("DataFormatsHeavyIonEvent_LinkDef",(G__incsetup)(&G__cpp_setupDataFormatsHeavyIonEvent_LinkDef)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDataFormatsHeavyIonEvent_LinkDef() { G__remove_setup_func("DataFormatsHeavyIonEvent_LinkDef"); }
};
G__cpp_setup_initDataFormatsHeavyIonEvent_LinkDef G__cpp_setup_initializerDataFormatsHeavyIonEvent_LinkDef;

