#!/bin/bash
#PBS -l nodes=1
#PBS -l mem=8000mb
#PBS -l pmem=8000mb
#PBS -l walltime=24:00:00
#PBS -o /home/xuq7/tmp/flow/CMSSW_5_3_8_HI_patch2/src/Analysis/SkimPFCand/test/pbs/tracktest/joboutput/job${TRIGNAME}_${DATASET}_$I.out
#PBS -j oe

cd $PBS_O_WORKDIR
pwd
echo $PBS_NODEFILE
echo $HOSTNAME

#source /gpfs21/grid/grid-app/cmssoft/cms/cmsset_default.sh
#eval `scramv1 runtime -sh`

#source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=slc5_amd64_gcc462

cd /home/xuq7/tmp/flow/CMSSW_5_3_8_HI_patch2/src
#cmsenv
eval `scramv1 runtime -sh`
cd /home/xuq7/tmp/flow/CMSSW_5_3_8_HI_patch2/src/Analysis/SkimPFCand/test/pbs/tracktest

cmsRun pPbFlowCorrSkim_${TRIGNAME}_cfg.py $I $DATASET $BEGIN $END

echo "Done!"

exit 0
