#!/bin/bash
#PBS -l nodes=1
#PBS -l mem=4000mb
#PBS -l pmem=4000mb
#PBS -l walltime=10:00:00
#PBS -o .output
#PBS -j oe

cd $PBS_O_WORKDIR
pwd
echo $PBS_NODEFILE
echo $HOSTNAME
if [ -f /tmp/x509up_u171345 ]
 then
	echo "grid file exist!"
 else 	
	echo "no grid file!"
	cp /home/xuq7/tmp/x509up_u171345 /tmp/x509up_u171345
	echo "copy success:" $?
fi

export SCRAM_ARCH=slc6_amd64_gcc472
cd /home/xuq7/CMSSW_6_2_3_patch1/src
eval `scramv1 runtime -sh`
cd /home/xuq7/CMSSW_6_2_3_patch1/src/jetRpA/RpA
