#!/bin/bash
#PBS -l nodes=1
#PBS -l mem=2000mb
#PBS -l walltime=18:00:00
#PBS -j oe

echo $SHELL
cd $PBS_O_WORKDIR
pwd
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=slc5_amd64_gcc462
eval `scramv1 runtime -sh`

cmsRun anaGenJet_cfg.py output="$Z2OUTPUT" maxEvents="$Z2MAXEVENTS" processType="$Z2PROCESSTYPE" ptHatLow="$Z2PTHATLOW" ptHatHigh="$Z2PTHATHIGH" sqrtS="$Z2ENERGY" applyPthatCut="$Z2APPLYCUT" &> run-$Z2ENERGY-$Z2PTHATLOW-$Z2PTHATHIGH-Z2.log

exit 0
