#!/bin/bash
#PBS -l nodes=1
#PBS -l mem=4000mb
#PBS -l walltime=12:00:00
#PBS -j oe

cd $PBS_O_WORKDIR
pwd
echo $PBS_NODEFILE
echo $HOSTNAME

source /gpfs21/grid/grid-app/cmssoft/cms/cmsset_default.sh
eval `scramv1 runtime -sh`
time cmsRun ana_cfg.py  \
            outputFile=file:ana_b0__#_SEQ_#.root \
            inputFiles=file:/scratch/appelte1/HYDJET_b0_612_Phase1/reco_b0__#_SEQ_#.root

exit 0
