void Drawhisto(){	
	gStyle->SetOptStat(kFALSE);
	gStyle->SetErrorX(0);
	TFile *fin = TFile::Open("PythiaMBhistos.root");
	TH1D* hratioplus = (TH1D*)fin->Get("NjetratioPlus");
	TCanvas *c1 = new TCanvas();
	c1->SetTickx(1);
	c1->SetTicky(1);
	hratioplus->GetXaxis()->SetTitle("#Sigma E_{T} (2.9<#eta<5.2) (GeV)");
	hratioplus->GetXaxis()->SetRangeUser(0,30);
	hratioplus->GetYaxis()->SetRangeUser(0,0.07);
	hratioplus->GetYaxis()->SetTitle("N_{jet}/N_{evt}");
	hratioplus->SetMarkerSize(1);
	hratioplus->SetMarkerStyle(20);
	hratioplus->SetMarkerColor(1);
	hratioplus->SetLineColor(1);
	hratioplus->Draw("P");
	TLatex *tl = new TLatex();
	tl->SetTextSize(0.045);
	tl->SetNDC();
	TLegend *tg = new TLegend(0.15,0.7,0.6,0.75);
	tg->SetTextSize(0.045);
	tg->SetFillColor(0);
	tg->SetBorderSize(0);
	tg->AddEntry(hratioplus,"5.02TeV, Z2Star Tune");
	tg->Draw("same");
	tl->DrawLatex(0.2,0.85,"Pythia 6");
	tl->DrawLatex(0.2,0.8,"anti-k_{T} R=0.3 PF jets, E_{T} > 20 GeV, |#eta| < 2.8");
	c1->Print("jetYratioHFPlus.png");
	c1->Print("jetYratioHFPlus.pdf");
}
