#!/bin/bash
#PBS -l nodes=1
#PBS -l mem=4000mb
#PBS -l pmem=4000mb
#PBS -l walltime=15:00:00
#PBS -o joblog.output
#PBS -j oe

cd $PBS_O_WORKDIR
pwd
echo $PBS_NODEFILE
echo $HOSTNAME

export SCRAM_ARCH=slc6_amd64_gcc472
cd /home/xuq7/CMSSW_6_2_3_patch1/src
eval `scramv1 runtime -sh`

cd /home/xuq7/CMSSW_6_2_3_patch1/src/jetRpA/RpA/TreeAna

export TRIG="Jet40"

root -l -b analyzeRpATree.C

exit 0



